version: "3.9"

services:
  native:
    build:
      context: .
      dockerfile: native/Dockerfile
    volumes:
      - ./results:/results
    env_file: .env

  wasm:
    build:
      context: .
      dockerfile: wasm/Dockerfile
    volumes:
      - ./results:/results
    env_file: .env
    shm_size: '256mb'
